CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024
CONFIG_MAIN_STACK_SIZE=1024
CONFIG_PM_DEVICE=y
CONFIG_ZERO_LATENCY_LEVELS=1
CONFIG_LOG=y
CONFIG_PARTITION_MANAGER_ENABLED=y
CONFIG_NRFX_GPIOTE_NUM_OF_EVT_HANDLERS=1
CONFIG_HWINFO=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y
CONFIG_ENTROPY_NRF5_THR_THRESHOLD=4
CONFIG_ENTROPY_NRF5_ISR_THRESHOLD=12
CONFIG_LED=y
CONFIG_PINCTRL=y
CONFIG_RTC=y
CONFIG_BT=y
CONFIG_LOG_BACKEND_SWO=y
CONFIG_HW_STACK_PROTECTION=y
CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_BOARD_TAPT=y
CONFIG_SENSOR=y
CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_POWEROFF=y

# Bluetooth advertisment config
CONFIG_BT_DEVICE_NAME="Tapt"
